name = "TQK"
uuid = "efc8405c-6321-11f0-3375-f52ce379e5a0"
authors = ["Niels Mandrus"]

[deps]
ArgCheck = "dce04be8-c92d-5529-be00-80e4d2c0e197"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
BlackBoxOptim = "a134a8b2-14d6-55f6-9291-3336d3ab0209"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
CondaPkg = "992eb4ea-22a4-4c89-a5bb-47a3300528ab"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
DrWatson = "634d3b9d-ee7a-5ddf-bec9-22491ea816e1"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
LIBSVM = "b1bec4e5-fd48-53fe-b0cb-9723c09d164b"
LRUCache = "8ac3fa9e-de4c-5943-b1dc-09c6b5f20637"
LanguageServer = "2b0e0bc5-e4fd-59b4-8912-456d1b03d8d7"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
MLUtils = "f1d291b0-491e-4a28-83b9-f70985020b54"
Manifolds = "1cead3c2-87b3-11e9-0ccd-23c62b72b94e"
MultivariateStats = "6f286f6a-111f-5878-ab1e-185364afe411"
Optimization = "7f7a1694-90dd-40f0-9382-eb1efda571ba"
OptimizationBBO = "3e6eede4-6085-4f62-9a71-46d9bc1eb92b"
OptimizationManopt = "e57b7fff-7ee7-4550-b4f0-90e9476e9fb6"
OptimizationOptimJL = "36348300-93cb-4f02-beb5-3c3902f8871e"
OptimizationOptimisers = "42dfb2eb-d2b4-4451-abcd-913932933ac1"
PProf = "e4faabce-9ead-11e9-39d9-4379958e3056"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
ProfileView = "c46f51b8-102a-5cf2-8d2c-8597cb0e0da7"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
PythonCall = "6099a3de-0909-46bc-b1f4-468b9a2dfc0d"
RDatasets = "ce6b1742-4840-55fa-b093-852dadbb1d8b"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
StructTypes = "856f2bd8-1eba-4b0a-8007-ebc267875bd4"
SymEngine = "123dc426-2d89-5057-bbad-38513e3affd8"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Yao = "5872b779-8223-5990-8dd0-5abbb0748c8c"
YaoAPI = "0843a435-28de-4971-9e8b-a9641b2983a8"
YaoBlocks = "418bc28f-b43b-5e0b-a6e7-61bbc1a2c1df"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[compat]
ArgCheck = "2.5.0"
BenchmarkTools = "1.6.0"
BlackBoxOptim = "0.6.3"
CSV = "0.10.15"
Combinatorics = "1.0.3"
CondaPkg = "0.2.33"
DataFrames = "1.7.0"
Dates = "1.11.0"
DrWatson = "2.18.0"
JLD2 = "0.6.2"
JSON3 = "1.14.3"
LIBSVM = "0.8.1"
LinearAlgebra = "1.11.0"
Logging = "1.11.0"
MLUtils = "0.4.8"
Manifolds = "0.10.23"
MultivariateStats = "0.10.3"
Optimization = "4.4.0"
OptimizationBBO = "0.4.1"
OptimizationManopt = "1.0.0"
OptimizationOptimJL = "0.4.3"
OptimizationOptimisers = "0.3.8"
PProf = "3.2.0"
Parameters = "0.12.3"
Plots = "1.40.17"
ProfileView = "1.10.1"
PythonCall = "0.9.28"
RDatasets = "0.7.7"
Random = "1.11.0"
Statistics = "1.11.1"
StatsBase = "0.34.6"
StructTypes = "1.11.0"
SymEngine = "0.12.0"
Test = "1.11.0"
YaoAPI = "0.4.8"
Zygote = "0.7.10"
julia = "1.11.6"
